# Generated by Django 5.1.7 on 2025-05-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_securitysettings_systemconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitysettings',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='securitysettings',
            name='name',
        ),
        migrations.RemoveField(
            model_name='securitysettings',
            name='value',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='setting',
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='expiry_days',
            field=models.PositiveIntegerField(default=90, verbose_name='Expiration après (jours)'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='lockout_time',
            field=models.PositiveIntegerField(default=30, verbose_name='Durée de verrouillage (minutes)'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='max_attempts',
            field=models.PositiveIntegerField(default=5, verbose_name='Tentatives avant verrouillage'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='mfa_enabled',
            field=models.BooleanField(default=False, verbose_name='MFA activé'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='mfa_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('authenticator', 'Application Authenticator')], default='email', max_length=13, verbose_name='Méthode MFA'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='min_length',
            field=models.PositiveIntegerField(default=8, verbose_name='Longueur minimale'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='require_complexity',
            field=models.CharField(choices=[('low', 'Basique (lettres seulement)'), ('medium', 'Moyenne (lettres + chiffres)'), ('high', 'Élevée (lettres + chiffres + spéciaux)')], default='medium', max_length=6, verbose_name='Complexité requise'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='backup_frequency',
            field=models.CharField(choices=[('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='weekly', max_length=10, verbose_name='Fréquence de sauvegarde'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='backup_location',
            field=models.CharField(default='/backups', max_length=255, verbose_name='Emplacement de sauvegarde'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Notifications par email'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='notification_email',
            field=models.EmailField(default='notifications@example.com', max_length=254, verbose_name="Email d'envoi"),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='site_name',
            field=models.CharField(default='Mon Application', max_length=100, verbose_name='Nom du site'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='sms_notifications',
            field=models.BooleanField(default=False, verbose_name='Notifications SMS'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50, verbose_name='Fuseau horaire'),
        ),
    ]
