# Generated by Django 5.1.7 on 2025-05-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_securitysettings_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='last_backup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
