# Generated by Django 5.2.1 on 2025-05-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_patientrecord_id_and_more'),
    ]

    operations = [
    ]
