# Generated by Django 5.2.1 on 2025-05-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20250530_1847'),
    ]

    operations = [
    ]
