# Generated by Django 5.2.1 on 2025-05-30 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20250530_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalexam',
            name='location',
        ),
        migrations.RemoveField(
            model_name='medicalexam',
            name='status',
        ),
        migrations.RemoveField(
            model_name='medicalexam',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='is_protected',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='exam_type',
            field=models.CharField(choices=[('BLOOD', 'Analyse sanguine'), ('RADIO', 'Radiographie'), ('SCAN', 'Scanner'), ('OTHER', 'Autre')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
