# Generated by Django 5.2.1 on 2025-05-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_medicalexam_location_and_more'),
    ]

    operations = [
    ]
