# Generated by Django 5.2.1 on 2025-05-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20250530_1901'),
    ]

    operations = [
    ]
