# Generated by Django 5.2.3 on 2025-06-10 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20250530_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='last_consultation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='next_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='primary_doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
