# Generated by Django 5.2.3 on 2025-06-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_prescription_dispensed_at_prescription_dispensed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='critical_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='critical_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', 'Urgence vitale'), ('2', 'Urgence sérieuse'), ('3', 'Urgence mineure')], max_length=1),
        ),
    ]
