# Generated by Django 5.2.3 on 2025-06-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_medication_supplier_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='audit_retention_days',
            field=models.PositiveIntegerField(default=2555, verbose_name='Rétention des audits (jours)'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='detailed_logging',
            field=models.BooleanField(default=True, verbose_name='Journalisation détaillée'),
        ),
    ]
